CREATE SCHEMA IF NOT EXISTS gestao_rpa;

CREATE TABLE IF NOT EXISTS gestao_rpa.usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login TEXT NOT NULL UNIQUE,
  nome TEXT NOT NULL,
  senha_hash TEXT NOT NULL,
  perfil TEXT NOT NULL CHECK (perfil IN ('visualizacao', 'aprovador')),
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gestao_rpa.sessoes (
  sid TEXT PRIMARY KEY,
  sessao JSONB NOT NULL,
  expira_em TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS sessoes_expira_idx ON gestao_rpa.sessoes (expira_em);

CREATE TABLE IF NOT EXISTS gestao_rpa.solicitacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  grupo_id UUID NOT NULL,
  solicitante_id BIGINT NOT NULL REFERENCES gestao_rpa.usuarios(id),
  tipo_alvo TEXT NOT NULL CHECK (tipo_alvo IN ('rotina', 'automacao', 'robo')),
  automacao_id TEXT,
  rotina_id TEXT,
  schema_origem TEXT NOT NULL,
  tabela_origem TEXT NOT NULL,
  chave_registro JSONB NOT NULL,
  valores_anteriores JSONB NOT NULL,
  valores_propostos JSONB NOT NULL,
  estado TEXT NOT NULL DEFAULT 'Pendente' CHECK (estado IN ('Pendente', 'Aprovado', 'Recusado')),
  decisor_id BIGINT REFERENCES gestao_rpa.usuarios(id),
  justificativa TEXT,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  decidido_em TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS solicitacoes_solicitante_idx ON gestao_rpa.solicitacoes (solicitante_id, criado_em DESC);
CREATE INDEX IF NOT EXISTS solicitacoes_estado_idx ON gestao_rpa.solicitacoes (estado, criado_em DESC);
CREATE INDEX IF NOT EXISTS solicitacoes_grupo_idx ON gestao_rpa.solicitacoes (grupo_id, criado_em DESC);

CREATE TABLE IF NOT EXISTS gestao_rpa.auditoria (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT REFERENCES gestao_rpa.usuarios(id),
  solicitacao_id BIGINT REFERENCES gestao_rpa.solicitacoes(id),
  acao TEXT NOT NULL,
  detalhes JSONB NOT NULL DEFAULT '{}'::jsonb,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
